apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepper
  labels:
    name: pepper
    app: pepper
spec:
  selector:
    matchLabels:
      app: pepper
  replicas: 1
  template:
    metadata:
      labels:
        app: pepper
    spec:
      volumes:
        - name: production
          secret:
            secretName: pepper-production
      containers:
        - name: pepper
          image: minhducsun2002/pepper:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: production
            mountPath: "/app/config"
          env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: pepper-production-token
                key: DISCORD_TOKEN
          - name: NODE_ENV
            value: production