/** Object type */
export enum SvtType {
    NORMAL = 1,
    /** Only Mash gets to have Heroine type, I guess */
    HEROINE,
    COMBINE_MATERIAL,
    ENEMY,
    ENEMY_COLLECTION,
    SERVANT_EQUIP,
    STATUS_UP,
    SVT_EQUIP_MATERIAL,
    ENEMY_COLLECTION_DETAIL,
    ALL,
    COMMAND_CODE
}

/** Card type */
export enum CardType { ARTS = 1, BUSTER = 2, QUICK = 3, EXTRA = 4 };
/** Gender type */
export enum GenderType { Male = 1, Female = 2 }

/** Servant class type */
export enum ClassType {
    Saber = 1,
    Archer = 2,
    Lancer = 3,
    Rider = 4,
    Caster = 5,
    Assassin = 6,
    Berserker = 7,
    Shielder = 8,
    Ruler = 9,
    AlterEgo = 10,
    Avenger = 11,
    MoonCancer = 23,
    Foreigner = 25
}

/** Servant attribute */
export enum Attribute {
    STAR = 4,
    BEAST = 5,
    HUMAN = 1,
    EARTH = 3,
    HEAVEN = 2,
}

/** Base attack multiplier for servant (class-agnostic) */
export type AttackRate = number;
/** Action Points */
export type AP = number;
/** Servant level */
export type Level = number;
/** Chapter ID */
export type Chapter = number;
/** War ID */
export type War = number;
/** Spot ID */
export type Spot = number;
/** Damage distribution */
export type DamageDistribution = number[];
/** Item ID */
export type Item = number;

export enum FuncType {
    NONE = 0,
    ADD_STATE = 1,
    SUB_STATE = 2,
    DAMAGE = 3,
    DAMAGE_NP = 4,
    GAIN_STAR = 5,
    GAIN_HP = 6,
    GAIN_NP = 7,
    LOSS_NP = 8,
    SHORTEN_SKILL = 9,
    EXTEND_SKILL = 10,
    RELEASE_STATE = 11,
    LOSS_HP = 12,
    INSTANT_DEATH = 13,
    DAMAGE_NP_PIERCE = 14,
    DAMAGE_NP_INDIVIDUAL = 15,
    ADD_STATE_SHORT = 16,
    GAIN_HP_PER = 17,
    DAMAGE_NP_STATE_INDIVIDUAL = 18,
    HASTEN_NPTURN = 19,
    DELAY_NPTURN = 20,
    DAMAGE_NP_HPRATIO_HIGH = 21,
    DAMAGE_NP_HPRATIO_LOW = 22,
    CARD_RESET = 23,
    REPLACE_MEMBER = 24,
    LOSS_HP_SAFE = 25,
    DAMAGE_NP_COUNTER = 26,
    DAMAGE_NP_STATE_INDIVIDUAL_FIX = 27,
    DAMAGE_NP_SAFE = 28,
    CALL_SERVANT = 29,
    PT_SHUFFLE = 30,
    LOSS_STAR = 31,
    CHANGE_SERVANT = 32,
    CHANGE_BG = 33,
    DAMAGE_VALUE = 34,
    WITHDRAW = 35,
    FIX_COMMANDCARD = 36,
    SHORTEN_BUFFTURN = 37,
    EXTEND_BUFFTURN = 38,
    SHORTEN_BUFFCOUNT = 39,
    EXTEND_BUFFCOUNT = 40,
    CHANGE_BGM = 41,
    DISPLAY_BUFFSTRING = 42,
    EXP_UP = 101,
    QP_UP = 102,
    DROP_UP = 103,
    FRIEND_POINT_UP = 104,
    EVENT_DROP_UP = 105,
    EVENT_DROP_RATE_UP = 106,
    EVENT_POINT_UP = 107,
    EVENT_POINT_RATE_UP = 108,
    TRANSFORM_SERVANT = 109,
    QP_DROP_UP = 110,
    SERVANT_FRIENDSHIP_UP = 111,
    USER_EQUIP_EXP_UP = 112,
    CLASS_DROP_UP = 113,
    ENEMY_ENCOUNT_COPY_RATE_UP = 114,
    ENEMY_ENCOUNT_RATE_UP = 115,
    ENEMY_PROB_DOWN = 116,
}

export enum TargetType {
    SELF = 0,
    PT_ONE = 1,
    PT_ANOTHER = 2,
    PT_ALL = 3,
    ENEMY = 4,
    ENEMY_ANOTHER = 5,
    ENEMY_ALL = 6,
    PT_FULL = 7,
    ENEMY_FULL = 8,
    PT_OTHER = 9,
    PT_ONE_OTHER = 10,
    PT_RANDOM = 11,
    ENEMY_OTHER = 12,
    ENEMY_RANDOM = 13,
    PT_OTHER_FULL = 14,
    ENEMY_OTHER_FULL = 15,
    PTSELECT_ONE_SUB = 16,
    PTSELECT_SUB = 17,
    PT_ONE_ANOTHER_RANDOM = 18,
}

export enum Buff {
    NONE = 0,
    UP_COMMANDATK = 1,
    UP_STARWEIGHT = 2,
    UP_CRITICALPOINT = 3,
    DOWN_CRITICALPOINT = 4,
    REGAIN_NP = 5,
    REGAIN_STAR = 6,
    REGAIN_HP = 7,
    REDUCE_HP = 8,
    UP_ATK = 9,
    DOWN_ATK = 10,
    UP_DAMAGE = 11,
    DOWN_DAMAGE = 12,
    ADD_DAMAGE = 13,
    SUB_DAMAGE = 14,
    UP_NPDAMAGE = 15,
    DOWN_NPDAMAGE = 16,
    UP_DROPNP = 17,
    UP_CRITICALDAMAGE = 18,
    DOWN_CRITICALDAMAGE = 19,
    UP_SELFDAMAGE = 20,
    DOWN_SELFDAMAGE = 21,
    ADD_SELFDAMAGE = 22,
    SUB_SELFDAMAGE = 23,
    AVOIDANCE = 24,
    BREAK_AVOIDANCE = 25,
    INVINCIBLE = 26,
    UP_GRANTSTATE = 27,
    DOWN_GRANTSTATE = 28,
    UP_TOLERANCE = 29,
    DOWN_TOLERANCE = 30,
    AVOID_STATE = 31,
    DONOT_ACT = 32,
    DONOT_SKILL = 33,
    DONOT_NOBLE = 34,
    DONOT_RECOVERY = 35,
    DISABLE_GENDER = 36,
    GUTS = 37,
    UP_HATE = 38,
    ADD_INDIVIDUALITY = 40,
    SUB_INDIVIDUALITY = 41,
    UP_DEFENCE = 42,
    DOWN_DEFENCE = 43,
    UP_COMMANDSTAR = 50,
    UP_COMMANDNP = 51,
    UP_COMMANDALL = 52,
    DOWN_COMMANDALL = 60,
    DOWN_STARWEIGHT = 61,
    REDUCE_NP = 62,
    DOWN_DROPNP = 63,
    UP_GAIN_HP = 64,
    DOWN_GAIN_HP = 65,
    DOWN_COMMANDATK = 66,
    DOWN_COMMANSTAR = 67,
    DOWN_COMMANDNP = 68,
    UP_CRITICALRATE = 70,
    DOWN_CRITICALRATE = 71,
    PIERCE_INVINCIBLE = 72,
    AVOID_INSTANTDEATH = 73,
    UP_RESIST_INSTANTDEATH = 74,
    UP_NONRESIST_INSTANTDEATH = 75,
    DELAY_FUNCTION = 76,
    REGAIN_NP_USED_NOBLE = 77,
    DEAD_FUNCTION = 78,
    UP_MAXHP = 79,
    DOWN_MAXHP = 80,
    ADD_MAXHP = 81,
    SUB_MAXHP = 82,
    BATTLESTART_FUNCTION = 83,
    WAVESTART_FUNCTION = 84,
    SELFTURNEND_FUNCTION = 85,
    UP_GIVEGAIN_HP = 87,
    DOWN_GIVEGAIN_HP = 88,
    COMMANDATTACK_FUNCTION = 89,
    DEADATTACK_FUNCTION = 90,
    UP_SPECIALDEFENCE = 91,
    DOWN_SPECIALDEFENCE = 92,
    UP_DAMAGEDROPNP = 93,
    DOWN_DAMAGEDROPNP = 94,
    ENTRY_FUNCTION = 95,
    UP_CHAGETD = 96,
    REFLECTION_FUNCTION = 97,
    UP_GRANT_SUBSTATE = 98,
    DOWN_GRANT_SUBSTATE = 99,
    UP_TOLERANCE_SUBSTATE = 100,
    DOWN_TOLERANCE_SUBSTATE = 101,
    UP_GRANT_INSTANTDEATH = 102,
    DOWN_GRANT_INSTANTDEATH = 103,
    GUTS_RATIO = 104,
    DAMAGE_FUNCTION = 86,
    UP_DEFENCECOMMANDALL = 105,
    DOWN_DEFENCECOMMANDALL = 106,
    OVERWRITE_BATTLECLASS = 107,
    OVERWRITE_CLASSRELATIO_ATK = 108,
    OVERWRITE_CLASSRELATIO_DEF = 109,
    UP_DAMAGE_INDIVIDUALITY = 110,
    DOWN_DAMAGE_INDIVIDUALITY = 111,
    UP_DAMAGE_INDIVIDUALITY_ACTIVEONLY = 112,
    DOWN_DAMAGE_INDIVIDUALITY_ACTIVEONLY = 113,
    UP_NPTURNVAL = 114,
    DOWN_NPTURNVAL = 115,
    MULTIATTACK = 116,
    UP_GIVE_NP = 117,
    DOWN_GIVE_NP = 118,
    UP_RESISTANCE_DELAY_NPTURN = 119,
    DOWN_RESISTANCE_DELAY_NPTURN = 120,
    PIERCE_DEFENCE = 121,
    UP_GUTS_HP = 122,
    DOWN_GUTS_HP = 123,
    UP_FUNCGAIN_NP = 124,
    DOWN_FUNCGAIN_NP = 125,
    UP_FUNC_HP_REDUCE = 126,
    DOWN_FUNC_HP_REDUCE = 127,
    UP_DEFENCECOMMAN_DAMAGE = 128,
    DOWN_DEFENCECOMMAN_DAMAGE = 129,
    NPATTACK_PREV_BUFF = 130,
    FIX_COMMANDCARD = 131,
    DONOT_GAINNP = 132,
    FIELD_INDIVIDUALITY = 133,
    DONOT_ACT_COMMANDTYPE = 134,
    UP_DAMAGE_EVENT_POINT = 135,
}

export enum BuffAction {
    NONE = 0,
    COMMAND_ATK = 1,
    COMMAND_DEF = 2,
    ATK = 3,
    DEFENCE = 4,
    DEFENCE_PIERCE = 5,
    SPECIALDEFENCE = 6,
    DAMAGE = 7,
    DAMAGE_INDIVIDUALITY = 8,
    DAMAGE_INDIVIDUALITY_ACTIVEONLY = 9,
    SELFDAMAGE = 10,
    CRITICAL_DAMAGE = 11,
    NPDAMAGE = 12,
    GIVEN_DAMAGE = 13,
    RECEIVE_DAMAGE = 14,
    PIERCE_INVINCIBLE = 15,
    INVINCIBLE = 16,
    BREAK_AVOIDANCE = 17,
    AVOIDANCE = 18,
    OVERWRITE_BATTLECLASS = 19,
    OVERWRITE_CLASSRELATIO_ATK = 20,
    OVERWRITE_CLASSRELATIO_DEF = 21,
    COMMAND_NP_ATK = 22,
    COMMAND_NP_DEF = 23,
    DROP_NP = 24,
    DROP_NP_DAMAGE = 25,
    COMMAND_STAR_ATK = 26,
    COMMAND_STAR_DEF = 27,
    CRITICAL_POINT = 28,
    STARWEIGHT = 29,
    TURNEND_NP = 30,
    TURNEND_STAR = 31,
    TURNEND_HP_REGAIN = 32,
    TURNEND_HP_REDUCE = 33,
    GAIN_HP = 34,
    TURNVAL_NP = 35,
    GRANT_STATE = 36,
    RESISTANCE_STATE = 37,
    AVOID_STATE = 38,
    DONOT_ACT = 39,
    DONOT_SKILL = 40,
    DONOT_NOBLE = 41,
    DONOT_RECOVERY = 42,
    INDIVIDUALITY_ADD = 43,
    INDIVIDUALITY_SUB = 44,
    HATE = 45,
    CRITICAL_RATE = 46,
    AVOID_INSTANTDEATH = 47,
    RESIST_INSTANTDEATH = 48,
    NONRESIST_INSTANTDEATH = 49,
    REGAIN_NP_USED_NOBLE = 50,
    FUNCTION_DEAD = 51,
    MAXHP_RATE = 52,
    MAXHP_VALUE = 53,
    FUNCTION_WAVESTART = 54,
    FUNCTION_SELFTURNEND = 55,
    GIVE_GAIN_HP = 56,
    FUNCTION_COMMANDATTACK = 57,
    FUNCTION_DEADATTACK = 58,
    FUNCTION_ENTRY = 59,
    CHAGETD = 60,
    GRANT_SUBSTATE = 61,
    TOLERANCE_SUBSTATE = 62,
    GRANT_INSTANTDEATH = 63,
    FUNCTION_DAMAGE = 64,
    FUNCTION_REFLECTION = 65,
    MULTIATTACK = 66,
    GIVE_NP = 67,
    RESISTANCE_DELAY_NPTURN = 68,
    PIERCE_DEFENCE = 69,
    GUTS_HP = 70,
    FUNCGAIN_NP = 71,
    FUNC_HP_REDUCE = 72,
    FUNCTION_NPATTACK = 73,
    FIX_COMMANDCARD = 74,
    DONOT_GAINNP = 75,
    FIELD_INDIVIDUALITY = 76,
    DONOT_ACT_COMMANDTYPE = 77,
    DAMAGE_EVENT_POINT = 78,
}

export enum ValsType {
    Rate = 0,
    Turn = 1,
    Count = 2,
    Value = 3,
    Value2 = 4,
    UseRate = 5,
    Target = 6,
    Correction = 7,
    ParamAdd = 8,
    ParamMax = 9,
    HideMiss = 10,
    OnField = 11,
    HideNoEffect = 12,
    Unaffected = 13,
    ShowState = 14,
    AuraEffectId = 15,
    ActSet = 16,
    ActSetWeight = 17,
    ShowQuestNoEffect = 18,
    CheckDead = 19,
    RatioHPHigh = 20,
    RatioHPLow = 21,
    SetPassiveFrame = 22,
    ProcPassive = 23,
    ProcActive = 24,
    HideParam = 25,
    SkillID = 26,
    SkillLV = 27,
    ShowCardOnly = 28,
    EffectSummon = 29,
    RatioHPRangeHigh = 30,
    RatioHPRangeLow = 31,
    TargetList = 32,
    OpponentOnly = 33,
}

export enum ItemType {
    QP = 1,
    STONE = 2,
    AP_RECOVER = 3,
    AP_ADD = 4,
    MANA = 5,
    KEY = 6,
    GACHA_CLASS = 7,
    GACHA_RELIC = 8,
    GACHA_TICKET = 9,
    LIMIT = 10,
    SKILL_LV_UP = 11,
    TD_LV_UP = 12,
    FRIEND_POINT = 13,
    EVENT_POINT = 14,
    EVENT_ITEM = 15,
    QUEST_REWARD_QP = 16,
    CHARGE_STONE = 17,
    RP_ADD = 18,
    BOOST_ITEM = 19,
    STONE_FRAGMENTS = 20,
    ANONYMOUS = 21,
    RARE_PRI = 22,
    COSTUME_RELEASE = 23,
    ITEM_SELECT = 24,
}

export enum QuestType {
    MAIN = 1,
    FREE = 2,
    FRIENDSHIP = 3,
    EVENT = 5,
    HEROBALLAD = 6,
}

export enum QuestConsumeType {
    NONE = 0,
    AP = 1,
    RP = 2,
    ITEM = 3,
}