name: Linting check
on:
  push:
    paths:
    - 'src/**'
jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      name: Setup Node.js
      with:
        node-version: '14.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Running the lint
      run: yarn lint
